### ISSUE TITLE
머리부터 발끝까지 

### ISSUE THREAD

**Issue by stareta1202** [fernok/RSMI2#2]
핫 이슈

**Comment by fernok** [comment]
지난번 이슈는 왜 닫으셨나여

**Comment by stareta1202** [comment]
제가 아니라 형민쿤이 닫으시는 거 같은데여?

**Comment by stareta1202** [comment]
ㅎㅇ

**Comment by fernok** [comment]
https://www.hangeulaward.co.kr/

창의쿤에게 어울리는 한글창의경진대회 어떠신가요

**Comment by stareta1202** [comment]
고파스에 글 올렸는데, 추천수 60 넘었어요

**Comment by stareta1202** [comment]
오예 추천수 110개 넘었다

**Comment by fernok** [comment]
어디있어요 왜 난 못찾겠지..

**Comment by stareta1202** [comment]
미국식 조크

**Comment by fernok** [comment]
![image](https://user-images.githubusercontent.com/54169293/118613615-df897780-b7f9-11eb-84ef-4e81487aa1e1.png)

아 실수했자나여

**Comment by stareta1202** [comment]
아니 이건 좀 너무하네;
수도 젬

**Comment by fernok** [comment]
아 실수로 차단해서 해제하려했더니 일주일 지나야되네;;
